### ISSUE TITLE
Why only consider video playing when app is TV or Computers?

### ISSUE THREAD

**Issue by lexpostma** [cristian5th/homebridge-appletv#9]
Hi Cristian, I found your repo yesterday and configured it all on my Raspberry Pi with `homebridge-cmd4` and `pyat`. What a great script and guide you wrote to make it all work! Thank you for this.

I did have a question about you choice to only consider "ATV Video Play" to be ON for the TV app (`TVWatchList`) and Computers app (`TVHomeSharing`). Why is that? What about other streaming apps like Disney+, HBO Max, Netflix etc? I miss an explanation for your choice to separate "ATV Play" and "ATV Video Play" in the readme, what's the goal for splitting between these?

**Comment by cristian5th** [comment]
Hi Lex.

This is just my personal preference as I don't use any of the apps that you mention. But you are right, I should mention it in the readme so everyone can adapt it to their needs. Actually, the best is not get the application in use as this is taking too long time to process.

**Comment by cristian5th** [comment]
Readme has been updated
